
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: python setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system_setup.yaml
