- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml

- name: copying mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: connnect to mongodb catalogue
  ansible.builtin.command: mongosh mongodb.someshwar.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: load products into mongodb
  ansible.builtin.shell: mongosh --host mongodb.someshwar.fun </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system_setup.yaml
